// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Update to your new project
const SUPABASE_URL = "https://ddhntljaamudkquaryrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkaG50bGphYW11ZGtxdWFyeXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTMwNTQsImV4cCI6MjA2NDcyOTA1NH0.oHK99SrJJxdyxhRh3tEX6px_ezwjXPsVcYoL6vVbkDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);